networks:
  sep4-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:

  frontend:
    image: oliwierwijas/smart-home-frontend:latest
    container_name: 'sep-frontend-container'
    ports:
      - "3000:3000"
    networks:
      sep4-network:
        ipv4_address: 172.28.0.4

  tcp-listener:
    image: vlaad08/smart-home-server:latest
    container_name: 'sep-backend-tcp-listener-container'
    environment:
      - DATABASE_HOST=smart-homel.postgres.database.azure.com
      - DATABASE_NAME=smart_home
      - DATABASE_USER=sep_user
      - DATABASE_PASSWORD=Semester4Password
      - SERVER_ADDRESS=172.28.0.2
    ports:
      - "6868:6868"
    networks:
      sep4-network:
        ipv4_address: 172.28.0.2

  web-api:
    image: vlaad08/smart-home:latest
    container_name: 'sep-backend-webapi-container'
    environment:
      - DATABASE_HOST=smart-homel.postgres.database.azure.com
      - DATABASE_NAME=smart_home
      - DATABASE_USER=sep_user
      - DATABASE_PASSWORD=Semester4Password
      - SERVER_ADDRESS=172.28.0.2
    ports:
      - "8080:80"
    networks:
      sep4-network:
        ipv4_address: 172.28.0.3
