version: "3.8"
services:
  frontend:
    build:
      context: ./
    container_name: 'sep-frontend-container'
    image: 'frontend:v1'
    ports:
      - 3000:3000
#    depends_on:
#      - backend


volumes:
  db:
    driver: local