version: "3.8"
services:
  backend:
    image: vlaad08/smart-home:latest
    container_name: 'sep-backend-container'
    ports:
      - 8080:80

  frontend:
    build:
      context: ./
    container_name: 'sep-frontend-container'
    image: 'frontend:v1'
    ports:
      - 3000:3000
    depends_on:
      - backend


volumes:
  db:
    driver: local