version: "3.8"
services:
  backend-server:
    image: vlaad08/smart-home-server:latest
    container_name: 'sep-backend-server-container'
    ports:
      - 6868:6868

  backend-webapi:
    image: vlaad08/smart-home:latest
    container_name: 'sep-backend-webapi-container'
    ports:
      - 8080:80

  frontend:
    build:
      context: ./
    container_name: 'sep-frontend-container'
    image: 'frontend:v1'
    ports:
      - 3000:3000
    depends_on:
      - backend-webapi


volumes:
  db:
    driver: local