name: Image pushed to DockerHub

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  docker-login:
    name: Login to Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push the web application
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart-home-frontend:latest