name: CD - Deploy to Minikube using GitHub Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  job1:
    name: Build and Deploy to Minikube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build Images
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker compose build
          echo -n "Verifying images: "
          docker images
          echo "Images build successfully"
      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.24.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin/kompose
      - name: Deploy to minikube
        run: |
          kompose convert
          kubectl apply -f tcp-listener-deployment.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f tcp-listener-service.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f web-api-deployment.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f web-api-service.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f frontend-deployment.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl apply -f frontend-service.yaml 2>&1 >/dev/null | tee /dev/stderr
          kubectl get all
          kubectl get pods
          echo "Deployment completed successfully"
          sleep 60
      - name: Test backend service URLs
        run: |
          echo "SERVICE_URL=$(minikube service web-api --url)"
          kubectl port-forward service/web-api 8080:8080 &> /dev/null &
          sleep 5
          kubectl port-forward service/web-api 8080:8080 &> /dev/null &
      - run: |
          curl -i http://localhost:8080/
      - name: Test frontend service URLs
        run: |
          echo "SERVICE_URL=$(minikube service frontend --url)"
          kubectl port-forward service/frontend 3000:3000 &> /dev/null &
          sleep 5
          kubectl port-forward service/frontend 3000:3000 &> /dev/null &
      - run: |
          curl -i http://localhost:3000/
      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete