name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  graph-component-tests:
    name: Unit tests - Graph Component
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Start containers
        run: |
          docker compose build
          docker compose up -d
  
      - name: Install dependencies
        run: |
          npm install
          npm install typescript --save-dev
          npm install date-fns
      
      - name: Run tests
        run: npm run test test/MyHome/GraphComponent

  house-component-tests:
    name: Unit tests - House Component
    runs-on: ubuntu-latest
    needs: graph-component-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Run tests
        run: |
          npm run test test/MyHome/HouseComponent
          npm run test MyHome.test.js

  myprofile-page-tests:
    name: Unit tests - MyProfile page components
    runs-on: ubuntu-latest
    needs: house-component-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Run tests
        run: | 
          npm run test test/MyProfile
          npm run test LockerPopUp.test.js

  signup-login-pages-tests:
    name: Unit tests - SignUp / Login components
    runs-on: ubuntu-latest
    needs: myprofile-page-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Run tests
        run: npm run test test/SignUpLogin

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: signup-login-pages-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Run Jest tests
        run: npm run test test/hooks

      - name: Stop containers
        run: docker compose down